package info.tonyl.pokeapi.constants;

public class PokeApiEndpoint {
	// Endpoints for all services
	public static final String BERRY = "berry";
	public static final String BERRY_FIRMNESS = "berry-firmness";
	public static final String BERRY_FLAVOR = "berry-flavor";
	public static final String CONTEST_TYPE = "contest-type";
	public static final String CONTEST_EFFECT = "contest-effect";
	public static final String SUPER_CONTEST_EFFECT = "super-contest-effect";
	public static final String ENCOUNTER_METHOD = "encounter-method";
	public static final String ENCOUNTER_CONDITION = "encounter-condition";
	public static final String ENCOUNTER_CONDITION_VALUE = "encounter-condition-value";
	public static final String EVOLUTION_CHAIN = "evolution-chain";
	public static final String EVOLUTION_TRIGGER = "evolution-trigger";
	public static final String GENERATION = "generation";
	public static final String POKEDEX = "pokedex";
	public static final String VERSION = "version";
	public static final String VERSION_GROUP = "version-group";
	public static final String ITEM = "item";
	public static final String ITEM_ATTRIBUTE = "item-attribute";
	public static final String ITEM_CATEGORY = "item-category";
	public static final String ITEM_FLING_EFFECT = "item-fling-effect";
	public static final String ITEM_POCKET = "item-pocket";
	public static final String LOCATION = "location";
	public static final String LOCATION_AREA = "location-area";
	public static final String PAL_PARK_AREA = "pal-park-area";
	public static final String REGION = "region";
	public static final String MACHINE = "machine";
	public static final String MOVE = "move";
	public static final String MOVE_AILMENT = "move-ailment";
	public static final String MOVE_BATTLE_STYLE = "move-battle-style";
	public static final String MOVE_CATEGORY = "move-category";
	public static final String MOVE_DAMAGE_CLASS = "move-damage-class";
	public static final String MOVE_LEARN_METHOD = "move-learn-method";
	public static final String MOVE_TARGET = "move-target";
	public static final String ABILITY = "ability";
	public static final String CHARACTERISTIC = "characteristic";
	public static final String EGG_GROUP = "egg-group";
	public static final String GENDER = "gender";
	public static final String GROWTH_RATE = "growth-rate";
	public static final String NATURE = "nature";
	public static final String POKEATHLON_STAT = "pokeathlon-stat";
	public static final String POKEMON = "pokemon";
	public static final String POKEMON_COLOR = "pokemon-color";
	public static final String POKEMON_FORM = "pokemon-form";
	public static final String POKEMON_HABITAT = "pokemon-habitat";
	public static final String POKEMON_SHAPE = "pokemon-shape";
	public static final String POKEMON_SPECIES = "pokemon-species";
	public static final String STAT = "stat";
	public static final String TYPE = "type";
	public static final String LANGUAGE = "language";
}
